### ISSUE TITLE
Min isotope correction

### ISSUE THREAD

**Issue by chambm** [compomics/compomics-utilities#14]
I'm not sure how this is supposed to work, but it seems messed up. The default is zero, yet in `IdentificationParametersInputBean.java` it is tested to be a positive integer.
```
if (aLine.hasOption(IdentificationParametersCLIParams.MIN_ISOTOPE.id)) {
            String arg = aLine.getOptionValue(IdentificationParametersCLIParams.MIN_ISOTOPE.id);
            if (!CommandParameter.isPositiveInteger(IdentificationParametersCLIParams.MIN_ISOTOPE.id, arg, true)) {
                return false;
            }
        }
```

Shouldn't this parameter be allowed to be negative?

**Comment by hbarsnes** [comment]
Hi Matt,

Yes, this is clearly an error in our checking of the command line input parameter. Thanks for pointing this out. We'll correct it and release a new version next week.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Matt,

A new version of utilities (v4.8.8) has now been deployed fixing the issue with the isotope range setting via the command line. New versions of all the tools using this feature have also been released.

Best regards,
Harald
