### ISSUE TITLE
issue with DeNovoGUI-1.14.5

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/compomics-utilities#15]
Hi, I am not having any luck with DeNovoGUI command line interface. I get the following errors for the identification parameter CLI:
[denovopar.txt](https://github.com/compomics/compomics-utilities/files/718363/denovopar.txt)

I get the following error message with the DeNovoGUI CLI:
[ucd256ma_denovo.txt](https://github.com/compomics/compomics-utilities/files/718364/ucd256ma_denovo.txt)

I tried un-installing and then re-installing DeNovoGUI-1.14.5 to no avail.
Thank you in advance for your help!

Best wishes,

Carla Uranga

**Comment by hbarsnes** [comment]
Hi Carla,

Thanks for telling us about this. Can you try this beta version of DeNovoGUI to see if it solves the issues: http://vedlegg.uib.no/?id=7080f7010df83e57123adf4612bbd01b?

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
Sure, I love these proteomics tools quite a bit, there are so many shortcuts I wish they had for post-sequencing analysis. I wish I knew how to program! The Beta version did work, except that  pNovo is still not activating or working, so I am going with Novor and PepNovo for now. Thanks again.

Best wishes,

Carla Uranga

**Comment by hbarsnes** [comment]
Hi Carla,

DeNovoGUI v1.15.0 has just been released fixing the issues with the command line.

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
Super sweet, you guys are fast, looking forward to trying it out! Do you
guys have any proteomics tools for differential expression? Best wishes and
greetings from a member of the science rebellion in Mexico!

**Comment by hbarsnes** [comment]
Hi Carla,

The only thing we have at the moment is Reporter (http://compomics.github.io/projects/reporter.html) for iTRAQ and TMT quantification.

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
So there is nothing for empai yet? Or based on spectral counts?

Best wishes,

Carla

**Comment by hbarsnes** [comment]
Hi Carla,

Spectral counting is included in PeptideShaker. You can choose between emPAI or NSAF. See the column called "MS2 Quant".

Best regards,
Harald
