### ISSUE TITLE
Peptide Shaker CLI

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/compomics-utilities#17]
Hi, the Peptide Shaker CLI instruction website is down, for some reason. Is Peptide Shaker OK for 3-4GB Orbitrap data files?

**Comment by hbarsnes** [comment]
The PeptideShaker command line pages should be back online soon. In the meantime you can access them here: https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI.

> Is Peptide Shaker OK for 3-4GB Orbitrap data files?

Yes, should be ok as long as you give is enough memory.

**Comment by hbarsnes** [comment]
The standard PeptideShaker CLI web page is now back online: http://compomics.github.io/peptide-shaker/wiki/peptideshakercli.html.

**Comment by carlaurangasolis** [comment]
I am giving it an Xmx of 500G, and even with the new version (Peptideshaker-1.15.0) I am getting this error message:

java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:567)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:219)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:931)

These are my command line arguments:
java -Djava.awt.headless=true -Xmx500G -cp PeptideShaker-1.15.0.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment "L1pep" -sample "MXL28" -replicate 1 -spectrum_files "L1.mgf" -id_params "HCD.par" -identification_files "L1_out.zip" -out "/LUSTRE/curanga/proteomica/Orb/L1.cpsx"

Thank you!

**Comment by hbarsnes** [comment]
You have to provide the complete path to the input files, i.e. the mgf, par and identification files. If you change this it should work.
