### ISSUE TITLE
Get MolecularFormula from Selenocysteine containing peptide

### ISSUE THREAD

**Issue by cctsou** [compomics/compomics-utilities#19]
Hi, 

I am trying to generate MolecularFormula from a rare Selenocysteine containing peptide using the following codes.

```
String pepseq="AASUBR";
AASequenceImpl aaseq=new AASequenceImpl(pepseq);
MolecularFormula formula = new MolecularFormula(aaseq);
```
It threw null exception at MolecularFormula() where it seems like elements.txt does not have definition for amino acid U (Selenocysteine). Since selenocysteine has Se element which is not listed in the top of elements.txt so I figured it may take more efforts to add this amino acid. Could you help me or guide me where should I modify the codes make it worked?

Thanks a lot,

**Comment by mvaudel** [comment]
Hi,

Sorry this is some rather old code, may we get some more input on what you want to do?

Would [AminoAcidSequence](https://github.com/compomics/compomics-utilities/blob/master/src/main/java/com/compomics/util/experiment/biology/AminoAcidSequence.java) do what you need?

Best regards,

Marc

**Comment by cctsou** [comment]
Hi Marc,

Thank you for the response, I am using it for for calculating isotope pattern. 

```
AASequenceImpl AAimple=new AASequenceImpl(Sequence);
formula=new MolecularFormula(AAimple);
IsotopicDistribution calc = new IsotopicDistribution(formula);   
```  

Is it possible to generate MolecularFormula from AminoAcidSequence?

Thanks,
Chih-Chiang

**Comment by mvaudel** [comment]
Hi Chih-Chiang,

No sorry, I will need to check with the developers of this part of the code. We will keep you posted.

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
Hi Chih-Chiang,

We've just deployed utilities version 4.11.6 which adds the required support for Selenocysteine (thanks to @nielshulstaert). Please give the new version a go and let us know if you come across any new issues.

Best regards,
Harald

**Comment by cctsou** [comment]
Hi Harald,

It's awesome, thanks a lot.

Best,
Chih-Chiang
