### ISSUE TITLE
Tag matching error at end of protein sequence, utilities-4.11.19

### ISSUE THREAD

**Issue by Thys3Potgieter** [compomics/compomics-utilities#26]
Hi Team, I have found what seems to be an error in the output of PeptideMapper:
787.369,IVAS,113.087,LNAEMGRIVASL,A0A0S3S6D4,283

However the protein sequence ends with: LNAEMGRLV, so there are three amino acids added in the identified peptide.

My IdentificationParmetersCli settings where: prec tol 0.02 in Da, and frag tolerance 0.02 in Daltons.
I realize I am not using the latest version, and will let you know if I see it in the latest version when I have a chance to rerun my data.

Tag: 787.369,IVAS,113.087

Protein:
>tr|A0A0S3S6D4|A0A0S3S6D4_PHAAN

Kind regards,
Thys

**Comment by dominik-kopczynski** [comment]
Hi Thys,

thank you very much for reporting the errors :-) Can it be, that the protein sequence is not available in your previous post? I can only see the fasta header "tr|A0A0S3S6D4|A0A0S3S6D4_PHAAN". Did you use any PTMs?

Cheers,
Dominik

**Comment by Thys3Potgieter** [comment]
>tr|A0A0S3S6D4|A0A0S3S6D4_PHAAN Uncharacterized protein (Fragment) OS=Vigna angularis var. angularis GN=Vigan.05G186800 PE=4 SV=1
MKVWTLDAALQRCQWPRHFREILSQTILTGLISDPYAASRLINFSTRSALVPFDYSLRIF
NHLHNPNPFTWNTIMRAHFELQNNPHQAITLYKLFLAKHAKPDNYTYPIPLQCCAARVSD
FEGRELHAHVLRFGFRQDVYVRNTLINLYAICGRMSSARQVFEESPVWDLVSWNTVLAGY
VQAGNVKEAERVYRGMPERNTIASNSMIVLFGRKGCVEKARRIFDEVRWRDMDMVSWSAM
VSCYEQNEMCEEALVLFVEMKASGVTVDEIVVVSVVSACSRILNAEMGRLV

**Comment by Thys3Potgieter** [comment]
[A0A0S3S6D4.fasta.gz](https://github.com/compomics/compomics-utilities/files/1371662/A0A0S3S6D4.fasta.gz)

**Comment by Thys3Potgieter** [comment]
[identification.par (1).zip](https://github.com/compomics/compomics-utilities/files/1371667/identification.par.1.zip)

Thanks Dominik, the parameters are the same as my previous message. Sorry for the missing info!

**Comment by dominik-kopczynski** [comment]
Thank you Thys, I'll try to reproduce and fix the error ASAP :-)
Cheers
