### ISSUE TITLE
enzyme Trypsin, no P rule

### ISSUE THREAD

**Issue by jflucier** [compomics/compomics-utilities#33]
Hi,

how can I specify the enzyme "Trypsin, no P rule". Since it has a comma in the name this generates the following error when I call eu.isas.searchgui.cmd.IdentificationParametersCLI:

`
export __ENZYME_LIST="Trypsin, no P rule"
export __FIXED_MODS="Carbamidomethylation of C"
export __VARIABLE_MODS="Deamidation of N, Deamidation of Q, Oxidation of M, Pyrolidone from Q, Pyrolidone from E, Acetylation of protein N-term"

.....

|15:02:52|jflucier@ip32-centos7:[20180929_QEHFX3_ML_DH_EXP133_highPHrp_FRAC9]> java -cp $SEARCHGUI_JAR_PATH eu.isas.searchgui.cmd.IdentificationParametersCLI \
> -ms_low_mem_mode $__MS_LOW_MEM_MODE \
> -max_charge $__MAX_CHARGE \
> -xtandem_min_frag_mz $__XTANDEM_MIN_FRAG_MZ \
> -msgf_num_ptms $__MSGF_NUM_PTMS \
> -myrimatch_num_ptms $__MYRIMATCH_NUM_PTMS \
> -ms_amanda_instrument "'$__MS_AMANDA_INSTRUMENT'" \
> -comet_num_ptms $__COMET_NUM_PTMS \
> -comet_remove_meth $__COMET_REMOVE_METH \
> -tide_num_ptms $__TIDE_NUM_PTMS \
> -tide_use_neutral_losses $__TIDE_USE_NEUTRAL_LOSSES \
> -db $TEMPDIR/db/searchgui_db_concatenated_target_decoy.fasta \
> -out $TEMPDIR/searchgui.parameters \
> -enzyme "$__ENZYME_LIST" \
> -fixed_mods '"'"$__FIXED_MODS"'"'  \
> -variable_mods '"'"$__VARIABLE_MODS"'"' \
> -frag_tol $__FRAG_TOL \
> -frag_ppm $__FRAG_PPM \
> -prec_tol $__PREC_TOL \
> -prec_ppm $__PREC_PPM \
> -protein_fdr 0.001 \
> -msgf_instrument $__MSGF_INSTRUMENT

Enzyme Trypsin, no P rule not recognized. Please add enzyme using the EnzymeCLI command.

Run -usage to see the list of supported options and their input.

`

thanks for your help.

JF

**Comment by hbarsnes** [comment]
Hi JF,

Some of the enzymes were renamed a long time ago to avoid this particular issue. Try replacing "Trypsin, no P rule" with "Trypsin (no P rule)" and it should work.

Where did you find the enzyme name "Trypsin, no P rule" btw? Did we forget to update the documentation somewhere?

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald,

this information was taken from :

[https://github.com/compomics/searchgui/blob/master/resources/Andromeda/windows/conf/enzymes.xml]

Can you point me to a github file where all enzymes are defined?

I guess for these enzyme, the same naming rules apply:

-         Thermolysin (no P rule)

-         Lys-C (no P rule)

For this one, what is the valid name: Chymotrypsin, no P rule (FYWL) --> Chymotrypsin (no P rule (FYWL))??

thanks again for your help,
JF

**Comment by hbarsnes** [comment]
Hi JF,

> this information was taken from :
[https://github.com/compomics/searchgui/blob/master/resources/Andromeda/windows/conf/enzymes.xml]

Those are the Andromeda enzyme names, not the SearchGUI ones. :)

> Can you point me to a github file where all enzymes are defined?

You can find all of the names at the end of this file: https://github.com/compomics/compomics-utilities/blob/master/src/main/java/com/compomics/util/experiment/biology/EnzymeFactory.java.

Or by running `java -cp SearchGUI-3.3.17.jar com.compomics.cli.enzymes.EnzymesCLI -l`

Best regards,
Harald

**Comment by jflucier** [comment]
thanks alot for your help Harald.
