### ISSUE TITLE
Error accessing PeptideMapper

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/compomics-utilities#37]
Hi I am trying to install and use Peptide Mapper but get the following error:

 wget http://genesis.ugent.be/maven2/com/compomics/utilities/4.10.0/utilities-4.10.0.zip
--2020-05-13 13:27:20--  http://genesis.ugent.be/maven2/com/compomics/utilities/4.10.0/utilities-4.10.0.zip
Resolving genesis.ugent.be... 157.193.160.40
Connecting to genesis.ugent.be|157.193.160.40|:80... connected.
HTTP request sent, awaiting response... 404 Resource does not exist
2020-05-13 13:27:20 ERROR 404: Resource does not exist.

**Comment by dominik-kopczynski** [comment]
Hi Carla, thank you for your message. For utilities 4.10.0, there is no zip file, just the compiled jar file. However, I would recommend to you to use the most recent version of utilities, that is 4.12.16.
You can choose between:

wget http://genesis.ugent.be/maven2/com/compomics/utilities/4.10.0/utilities-4.10.0.jar

or 

wget http://genesis.ugent.be/maven2/com/compomics/utilities/4.12.16/utilities-4.12.16.zip

Cheers, Dominik

**Comment by CarlaCristinaUranga** [comment]
Awesome, thank you! One question, can we only use Uniprot databases right
now or can we adapt a custom database? If so is there a header syntax you
might be able to provide?

Best wishes,
Carla

**Comment by CarlaCristinaUranga** [comment]
Sorry I saw that you also accept generic FASTA files. I have a FASTA file
that works with PeptideShaker, but for some reason PeptideMapper reports an
error, stating it cannot open the FASTA file.

Best,
Carla

**Comment by dominik-kopczynski** [comment]
Hi Carla, thank you for the report. Is it possible to get the exact error message? The best would even be, if I could get the actual fasta file you are trying to load. So I can quickly reproduce the error and try to fix it asap.

**Comment by CarlaCristinaUranga** [comment]
Hi Dominik thank you so much I have attached a sample of the fasta, since
it is 1.1 GB it would be a problem to send over. The error I get is:

(base) [curanga@dell-17 utilities-4.12.16]$ Start reading FASTA file

Error: cound not open FASTA file


Here is my command line input:

java -cp utilities-4.12.16.jar
com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping
-p -InputFasta
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideMapper/FINAL5.fasta
-InputList
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideMapper/RPP1_pep.txt
-OutputResultList
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/PeptideMapper/Out
-UtilitiesParameterFile
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/proteomics/SearchGUI-4.0.0-beta/saliva_final.par
> RPP1_pep.log &

**Comment by dominik-kopczynski** [comment]
Hi Carla, thank you for the reply. The minimalist error messages that I implemented are not really helpful for bug tracking. Would it be fine for you when I open a cloud and you would upload the file? 
Plan b would be to split the file. Maybe the error occurs too, when load a fasta which only has the first 100 entries of your original fasta file. This would be way smaller. For the next version of PeptideMapper, I insert a proper logging and error messaging system ;-) Cheers

**Comment by CarlaCristinaUranga** [comment]
Yes that would be great! Whatever it takes to get this to work. I  have no
trouble sharing the complete fasta with you. How do I upload it? I will
also try the g drive. Thank you so much!

Carla

**Comment by dominik-kopczynski** [comment]
Hey, send you a gmail with the cloud information.

**Comment by dominik-kopczynski** [comment]
Hi Carla, the good news: there is nothing wrong with your fasta file. I assume that Java ran out of memory during the computation of the index. When I increased the memory size on my computer, I could ran PeptideMapper without problems. Please try to increase Javas maximum memory with:
java -Xmx16G [remaining command]
When this is still not solving your problem, then please clone the compomics repository, switch to "new_backend" brach, install the 5.0 beta version and try PeptideMapper with all its changes:

git clone https://github.com/compomics/compomics-utilities
cd compomics-utilities
git checkout new_backend
mvn install
cd target/utilities-5.X.X-foo/
java -Xmx16G -cp utilities-5.X.X-foo.jar com.compomics.cli.peptide_mapper.PeptideMapperCLI -p PATH/TO/FASTA_FILE.fasta PATH/TO/PEPTIDE_LIST.csv OUTPUT.csv

Cheers,
Dominik

**Comment by CarlaCristinaUranga** [comment]
Ok that is great. I am currently trying to install apache maven. I am
having a little trouble setting the path variable, but once I get this
going I will let you know. Thank you!

Best wishes,
Carla

**Comment by CarlaCristinaUranga** [comment]
Hi Dominik I was able to get maven working and ran maven install and got
the following errors:


[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] *BUILD FAILURE*

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] Total time:  20:30 min

[*INFO*] Finished at: 2020-05-15T10:04:39-07:00

[*INFO*]
*------------------------------------------------------------------------*

[*ERROR*] Failed to execute goal
org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar *(attach-javadocs)*
on project utilities: *MavenReportException: Error while creating archive: *

[*ERROR*] *Exit code: 1 -
/Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/CommandLineParser.java:73:
error: attribute not supported in HTML5: name*

[*ERROR*] *     * <a name="optionConstr"></a> This constructor requests the
command-line*

[*ERROR*] *          ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:126:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The general contract of <tt>finalize</tt> is that it is
invoked*

[*ERROR*] *                               ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:132:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * finalized. The <tt>finalize</tt> method may take any
action, including*

[*ERROR*] *                      ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:134:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * of <tt>finalize</tt>, however, is to perform cleanup
actions before*

[*ERROR*] *          ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:140:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The <tt>finalize</tt> method of class <tt>Object</tt>
performs no*

[*ERROR*] *           ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:140:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The <tt>finalize</tt> method of class <tt>Object</tt>
performs no*

[*ERROR*] *                                             ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:142:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * <tt>Object</tt> may override this definition.*

[*ERROR*] *       ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:145:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * invoke the <tt>finalize</tt> method for any given object.
It is*

[*ERROR*] *                  ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:151:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * After the <tt>finalize</tt> method has been invoked for
an object, no*

[*ERROR*] *                 ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/general/FileLoggerImplementation.java:158:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The <tt>finalize</tt> method is never invoked more than
once by a Java*

[*ERROR*] *           ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:329:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The general contract of <tt>finalize</tt> is that it is
invoked*

[*ERROR*] *                               ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:335:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * finalized. The <tt>finalize</tt> method may take any
action, including*

[*ERROR*] *                      ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:337:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * of <tt>finalize</tt>, however, is to perform cleanup
actions before*

[*ERROR*] *          ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:343:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The <tt>finalize</tt> method of class <tt>Object</tt>
performs no*

[*ERROR*] *           ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:343:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The <tt>finalize</tt> method of class <tt>Object</tt>
performs no*

[*ERROR*] *                                             ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:345:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * <tt>Object</tt> may override this definition.*

[*ERROR*] *       ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:348:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * invoke the <tt>finalize</tt> method for any given object.
It is*

[*ERROR*] *                  ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:354:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * After the <tt>finalize</tt> method has been invoked for
an object, no*

[*ERROR*] *                 ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/gui/JTableForDB.java:361:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * The <tt>finalize</tt> method is never invoked more than
once by a Java*

[*ERROR*] *           ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationImplementation.java:220:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     *     an execution of a Java application, the
<tt>hashCode</tt> method*

[*ERROR*] *                                                   ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationImplementation.java:222:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     *     used in <tt>equals</tt> comparisons on the object is
modified.*

[*ERROR*] *                   ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationImplementation.java:225:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * <li>If two objects are equal according to the
<tt>equals(Object)</tt>*

[*ERROR*] *                                                     ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationImplementation.java:230:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     *     method, then calling the <tt>hashCode</tt> method on
each of the*

[*ERROR*] *                                    ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationImplementation.java:237:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * class <tt>Object</tt> does return distinct integers for
distinct*

[*ERROR*] *             ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationTemplate.java:223:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     *     an execution of a Java application, the
<tt>hashCode</tt> method*

[*ERROR*] *                                                   ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationTemplate.java:225:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     *     used in <tt>equals</tt> comparisons on the object is
modified.*

[*ERROR*] *                   ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationTemplate.java:228:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * <li>If two objects are equal according to the
<tt>equals(Object)</tt>*

[*ERROR*] *                                                     ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationTemplate.java:233:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     *     method, then calling the <tt>hashCode</tt> method on
each of the*

[*ERROR*] *                                    ^*

[*ERROR*] */Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/src/main/java/com/compomics/util/protein/ModificationTemplate.java:240:
error: tag not supported in the generated HTML version: tt*

[*ERROR*] *     * class <tt>Object</tt> does return distinct integers for
distinct*

[*ERROR*] *             ^*

[*ERROR*]

[*ERROR*] *Command line was:
/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/bin/javadoc
@options @packages*

[*ERROR*]

[*ERROR*] *Refer to the generated Javadoc files in
'/Users/curanga/Desktop/compomics-utilities-master/compomics-utilities/docs/javadoc'
dir.*

[*ERROR*]

[*ERROR*] -> *[Help 1]*

[*ERROR*]

[*ERROR*] To see the full stack trace of the errors, re-run Maven with the
*-e* switch.

[*ERROR*] Re-run Maven using the *-X* switch to enable full debug logging.

[*ERROR*]

[*ERROR*] For more information about the errors and possible solutions,
please read the following articles:

[*ERROR*] *[Help 1]*
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

(base) curangalt-osx:compomics-utilities curanga$

**Comment by hbarsnes** [comment]
Hi Carla,

I'm afraid that some of the JavaDoc for our old code is not compatible with the latest versions of Java. You therefore either need to downgrade your Java version or comment out the maven-javadoc-plugin section in the utilities pom file. The latter is probably the easiest. Just search for and comment out or remove the whole section labeled "Create javadoc on build".

Best regards,
Harald

**Comment by dominik-kopczynski** [comment]
Hi Carla, do I see it correctly that you are using Java 14?

**Comment by CarlaCristinaUranga** [comment]
Hi, yes I am using JDK 14. Harald's solution worked well for getting it to
work with PeptideMapper. So PeptideMapper is working now. However, I see
you developed MPA portable, which is specifically for metaproteomics, so I
am trying to get this to work, with no success so far. I am also using
SearchGUI/PeptideShaker. What would be the difference between MPA portable
(I am using the CLI) and SearchGUI/Peptide Shaker?

Best wishes,
Carla

**Comment by mvaudel** [comment]
Hi,

MPA is specifically designed for metaproteomics, the main conceptual difference is that it can aggregate results at the taxon level, while PeptideShaker only works at the peptide and protein group levels. There are also many differences in the architecture/algorithm/implementation that are required for the handling of metaproteomics results. If you want to learn more about these, feel free to contact the developers, they are much more knowledgeable than us on this :-)

Hope it helps,

Marc

**Comment by CarlaCristinaUranga** [comment]
Ok wonderful thank you. So can PeptideShaker handle a fasta file with 4.3
million sequences in it? I got it to work with a smaller database but now
that I switched to a super database the program stops at unzipping the
identification files and goes from "R" server status to Sl, and it doesn't
proceed. About how long does the program take to move from Sl back to "R"
status? Thanks.

Best wishes,
Carla

**Comment by dominik-kopczynski** [comment]
Hi Carla, thank you for your message. We developed the indexing in PeptideShaker this way, that it should cope with big fasta files as long as the complete index fits into your memory. You said that you have 16G memory. Do you have the possibility to try PS on a bigger computer? 
What do you mean with "R" and "SI" status? Where do you see this information?

Cheers,
Dominik

**Comment by dominik-kopczynski** [comment]
After 6 months of inactivity, I am closing this thread. If you still have problems / issues, feel free to reactivate this thread or open a new issue.

Cheers,
Dominik
