### ISSUE TITLE
Running PeptideMapperCLI

### ISSUE THREAD

**Issue by hbckleikamp** [compomics/compomics-utilities#46]
Dear compomics,

I am trying to run the peptide mapper tool.

I have no problems running this example, from https://github.com/compomics/compomics-utilities/wiki/PeptideMapper:
(except that I replaced 4.10.0 with 4.12.0, since there is no utilities-4.10.0.zip)
wget http://genesis.ugent.be/maven2/com/compomics/utilities/4.10.0/utilities-4.10.0.zip
unzip utilities-4.10.0.zip
cd utilities-4.10.0
java -cp utilities-4.10.0.jar com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping -p exampleFiles/PeptideMapping/yeast.fasta exampleFiles/PeptideMapping/yeast-pep-1k.csv results.csv

However, when I try to run the PeptideMapperCLI example, from: https://github.com/compomics/compomics-utilities/wiki/PeptideMapperCLI
java -cp utilities-5.0.9.jar com.compomics.cli.peptide_mapper.PeptideMapperCLI -p exampleFiles/PeptideMapping/yeast.fasta exampleFiles/PeptideMapping/yeast-pep-1k.csv result-file.csv

I get the following error:

Exception in thread "main" java.lang.NullPointerException
        at com.compomics.cli.peptide_mapper.PeptideMapperCLI.handleParameters(PeptideMapperCLI.java:363)
        at com.compomics.cli.peptide_mapper.PeptideMapperCLI.main(PeptideMapperCLI.java:85)

**Comment by hbarsnes** [comment]
It seems like you are using an old version of utilities. Can you try upgrading to utilities-5.0.34? At least the given command line works fine in that version on my side.

**Comment by hbckleikamp** [comment]
Thanks Harold, this works indeed! I assumed 5.0.9 to be the most recent version since it was sorted at the bottom, but did not account for the 2nd digit.
