### ISSUE TITLE
PeptideMapper output doesn't map to tags

### ISSUE THREAD

**Issue by Thys3Potgieter** [compomics/compomics-utilities#56]
Dear Team, I am trying to update the MetaNovo software to run with a newer version of PeptideMapper as the old version is no longer available.

The output of PeptideMapper using utilities-4.11.19 and the following command includes the tags:
`com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping -t`
**1000.39,IDAA,128.095,LYEMFMGPIDAAK,Q1MFI6,633**

Thus I am able to link the tag that caused a match, with the peptide it corresponds to, and the protein that contains it.

But the command described in the tutorial doesn't work with the version described:
http://compomics.github.io/projects/compomics-utilities/wiki/PeptideMapper
(java -cp utilities-5.0.34.jar com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping)
![Screen Shot 2022-01-24 at 18 27 02](https://user-images.githubusercontent.com/10395695/150823193-5c198a21-ca36-4a36-8e6b-ee3020fb971f.png)

See error for version utilities-5.0.34 and the command `com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping -t <params>`:
`Error: Could not find or load main class com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping `
`Caused by: java.lang.ClassNotFoundException: com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping`

Further, replacing this with the command from here: http://compomics.github.io/projects/compomics-utilities/wiki/PeptideMapperCLI#example causes the error to go away but now the output looks different 
using the command `com.compomics.cli.peptide_mapper.PeptideMapperCLI -t `:

**HGSGSGQSSSYSPYGSGSGWSSSR,Q86YZ3,2424,** 

The tag information represented in the output is no longer there, meaning that I am unable to map the protein accessions to the tags themselves. Is this an error on my part or has the output stopped making sense for sequence tags? I can see that the output will still make sense for peptide mapping, which could explain how the bug crept in. However, even for  the cases of peptides the input sequence and the match may not be identical (eg in case of I/L equivalence) and therefore the original query sequence is still needed.

Thank you very much for looking into this,

**Comment by hbarsnes** [comment]
Thanks for lettings us know! The outdated command line in the PeptideMapper wiki page has now been updated (in the same way as you already figured out).

I've also re-added the missing information in the tag export and deployed a new version of utilities (v5.0.38) which should take care of the problem. If this is not the case, please let me know and I'll reopen the issue.

**Comment by Thys3Potgieter** [comment]
Thanks Harald!
