### ISSUE TITLE
Can't initiate the application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [compomics/compomics-utilities#6]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `rmcjband...@gmail.com` on 9 Jul 2015 at 6:06

**Comment by hbarsnes** [comment]
This issue was solved in later versions of the library. If this is not the case, please let us know and we'll reopen the issue.
